"""empty message

Revision ID: 364178dc4079
Revises: e58921b69df6
Create Date: 2023-01-16 14:36:57.353879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364178dc4079'
down_revision = 'e58921b69df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
